# Generated by Django 6.0.3 on 2026-03-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="can_create_worker",
            field=models.BooleanField(default=False),
        ),
    ]
