# Generated by Django 6.0.3 on 2026-03-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_position_can_create_worker"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="can_edit_tasks",
            field=models.BooleanField(default=False),
        ),
    ]
