# Generated by Django 6.0.3 on 2026-03-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_position_can_edit_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
