# Generated by Django 6.0.3 on 2026-03-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_worker_last_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="can_create_positions",
            field=models.BooleanField(default=False),
        ),
    ]
